core/urls.py
from django.urls import path
from core import views
from django.urls import path, include
from . import views
from core.passenger import views as passenger_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('sign-up/', views.sign_up, name='sign-up'),
    # Add other URL patterns for core app

    # Add the passenger app patterns
    path('passenger/', include((
        [
            path('', passenger_views.home, name="passenger-home"),
            path('profile/', passenger_views.profile_page, name="profile"),
            path('payment-method/', passenger_views.payment_method_page, name="payment-method"),
            path('book-a-taxi/', passenger_views.book_taxi_page, name="book-a-taxi"),
            path('my-trips/', passenger_views.my_trips_page, name="my-trips"),
            path('cancel-trip/<uuid:trip_id>/', passenger_views.cancel_trip, name='cancel-trip'),
        ],
        'passenger'
    ), namespace='passenger')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taximate/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from core import views as core_views
from core.passenger import views as passenger_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_views.home, name='home'),
    path('sign-up/', core_views.sign_up, name="sign-up"),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    
    # Passenger views
    path('passenger/', include(([
        path('', passenger_views.home, name="passenger-home"),
        path('profile/', passenger_views.profile_page, name="profile"),
        path('payment-method/', passenger_views.payment_method_page, name="payment-method"),
        path('book-a-taxi/', passenger_views.book_taxi_page, name="book-a-taxi"),
        path('my-trips/', passenger_views.my_trips_page, name="my-trips"),
        path('cancel-trip/<uuid:trip_id>/', passenger_views.cancel_trip, name='cancel-trip'),
    ], 'passenger'), namespace='passenger')),
    
    # Other URL patterns
    
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import User

class PassengerSignUpForm(forms.ModelForm):
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password', 'required': True}),
    )
    email = forms.EmailField(
        max_length=250,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email Address', 'required': True}),
    )
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username', 'required': True}),
    )
    first_name = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name', 'required': True}),
    )
    last_name = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name', 'required': True}),
    )

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email address is already registered.")
        return email

core/passenger/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from core.passenger import forms
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.conf import settings
import stripe
from core.models import Taxi, Passenger, MyTrips
from django.utils import timezone
import googlemaps
from googlemaps import convert
from googlemaps import distance_matrix
from django.utils.text import slugify
from .forms import TaxiBookingForm
from datetime import datetime
from django.utils.timezone import now
from .forms import BasicUserForm, BasicCustomerForm
from django.http import HttpResponseRedirect,HttpRequest
from core.models import TaxiPassenger,TaxiDriver,User
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from core.models import Passenger
from django.core.exceptions import ObjectDoesNotExist



User = get_user_model()

def home(request):
    return render(request, "welcome.html")



@login_required(login_url="/login/?next=/passenger/")
def profile_page(request):
    user_form = BasicUserForm(instance=request.user)
    passenger_form = BasicCustomerForm(instance=request.user.passenger)
    password_form = PasswordChangeForm(request.user)

    if request.method == "POST":
        if request.POST.get('action') == 'update_profile':
            user_form = BasicUserForm(request.POST, instance=request.user)
            passenger_form = BasicCustomerForm(request.POST, request.FILES, instance=request.user.passenger)
            if user_form.is_valid() and passenger_form.is_valid():
                user_form.save()
                passenger_form.save()

                messages.success(request, 'Profile updated successfully.')
                return redirect(reverse('passenger:profile'))

        elif request.POST.get('action') == 'update_password':
            password_form = PasswordChangeForm(request.user, request.POST)
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)

                messages.success(request, 'Password updated successfully.')
                return redirect(reverse('passenger:profile'))

    return render(request, 'passenger/profile.html', {
        "user_form": user_form,
        "passenger_form": passenger_form,
        "password_form": password_form,
    })



# BOOKING TAXI

@login_required(login_url="/login/?next=/passenger/")

def book_taxi_page(request):
    if not request.user.is_authenticated or not hasattr(request.user, 'passenger'):
        return redirect('login')

    if request.method == "POST":
        pickup_form = TaxiBookingForm(request.POST)
        if pickup_form.is_valid():
            passenger = request.user.passenger

            # Validate pickup address
            gmaps = googlemaps.Client(key=settings.GOOGLE_MAPS_API_KEY)
            pickup_address = pickup_form.cleaned_data['pickup_address']
            pickup_geocode_result = gmaps.geocode(pickup_address)
            if not pickup_geocode_result:
                messages.error(request, "Invalid pickup address. Please enter a valid address.")
                return redirect(reverse('passenger:book-a-taxi'))
            pickup_location = pickup_geocode_result[0]['geometry']['location']
            pickup_lat = pickup_location['lat']
            pickup_lng = pickup_location['lng']

            # Validate dropoff address
            dropoff_address = pickup_form.cleaned_data['dropoff_address']
            dropoff_geocode_result = gmaps.geocode(dropoff_address)
            if not dropoff_geocode_result:
                messages.error(request, "Invalid dropoff address. Please enter a valid address.")
                return redirect(reverse('passenger:book-a-taxi'))
            dropoff_location = dropoff_geocode_result[0]['geometry']['location']
            dropoff_lat = dropoff_location['lat']
            dropoff_lng = dropoff_location['lng']

            # Calculate the distance using Google Maps Distance Matrix API
            origins = f"{pickup_lat},{pickup_lng}"
            destinations = f"{dropoff_lat},{dropoff_lng}"
            result = gmaps.distance_matrix(origins, destinations, mode='driving')

            # Extract the distance value from the API response
            distance = result['rows'][0]['elements'][0]['distance']['value']
            # Convert distance to kilometers (optional)
            distance_km = distance / 1000

            # Create a new booking instance
            taxi_booking = Taxi(
                taxi_passenger=passenger,
                pickup_address=pickup_address,
                pickup_lat=pickup_lat,
                pickup_lng=pickup_lng,
                dropoff_address=dropoff_address,
                dropoff_lat=dropoff_lat,
                dropoff_lng=dropoff_lng,
                trip_distance=distance_km,
                pickup_datetime=datetime.now(),
                taxi_booking_status=Taxi.TRIP_BOOKED
            )
            taxi_booking.save()

            # Create MyTrips instance
            my_trip = MyTrips(
                booked_passenger=passenger,
                booked_taxi=taxi_booking,
            )
            my_trip.save()

            # Add success message
            messages.success(request, "Booking created successfully!")

            return redirect(reverse('passenger:my-trips'))
        else:
            # Add error messages for form fields with invalid data
            for field, errors in pickup_form.errors.items():
                for error in errors:
                    messages.error(request, f"Invalid {field}: {error}")
    else:
        pickup_form = TaxiBookingForm()

    return render(request, 'passenger/book-a-taxi.html', {
        "pickup_form": pickup_form,
    })
# CANCEL THE TRIP LOGIC

def cancel_trip(request, trip_id):
    try:
        trip = Taxi.objects.get(id=trip_id)
        trip.taxi_booking_status = Taxi.TRIP_CANCELLED  # Update the booking status to 'Trip Cancelled'
        trip.save()

        my_trip = MyTrips.objects.get(booked_taxi=trip)
        my_trip.save()

        messages.success(request, "Trip cancelled successfully!")
    except Taxi.DoesNotExist:
        messages.error(request, "Trip not found.")

    return redirect('passenger:my-trips')

#  PASSENGER TRIPS
@login_required(login_url="/login/?next=/passenger/")

def my_trips_page(request):
    try:
        passenger = request.user.passenger
        booked_trips = Taxi.objects.filter(taxi_passenger=passenger, taxi_booking_status=Taxi.TRIP_BOOKED).order_by('pickup_datetime')
        canceled_trips = Taxi.objects.filter(taxi_passenger=passenger, taxi_booking_status=Taxi.TRIP_CANCELLED).order_by('cancellation_time')

        trips = list(booked_trips) + list(canceled_trips)

        context = {
            'trips': trips,
        }

        return render(request, 'passenger/my-trips.html', context)

    except ObjectDoesNotExist:
        # Handle the case when the user does not have a related passenger object
        # You can adjust this part to fit your desired behavior or redirect the user to an appropriate page
        return render(request, 'passenger/my-trips.html', {'no_passenger': True})



#Payment Method

stripe.api_key = settings.STRIPE_SECRET_KEY

@login_required(login_url="/login/?next=/passenger/")

def payment_method_page(request):
    try:
        passenger = request.user.passenger
    except AttributeError:
        return redirect('login')

    if request.method == 'POST':
        stripe.PaymentMethod.detach(passenger.stripe_payment_method_id)
        passenger.stripe_payment_method_id = ''
        passenger.stripe_card_last4 = ''
        passenger.save()
        return redirect('passenger:payment-method')

    if not passenger.stripe_customer_id:
        customer = stripe.Customer.create()
        passenger.stripe_customer_id = customer['id']
        passenger.save()

    stripe_payment_methods = stripe.PaymentMethod.list(
        customer=passenger.stripe_customer_id,
        type='card',
    )

    if stripe_payment_methods and len(stripe_payment_methods.data) > 0:
        payment_method = stripe_payment_methods.data[0]
        passenger.stripe_payment_method_id = payment_method.id
        passenger.stripe_card_last4 = payment_method.card.last4
        passenger.save()
    else:
        passenger.stripe_payment_method_id = ''
        passenger.stripe_card_last4 = ''
        passenger.save()

    client_secret = stripe.SetupIntent.create(
        customer=passenger.stripe_customer_id,
        payment_method_types=['card'],
    ).client_secret

    return render(request, 'passenger/payment-method.html', {
        'passenger': passenger,
        'client_secret': client_secret,
        'STRIPE_API_PUBLIC_KEY': settings.STRIPE_API_PUBLIC_KEY,
    })

core/views.py
from django.urls import reverse_lazy
from .models import User,TaxiPassenger,TaxiDriver,Driver,Passenger
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from . import forms
from django.contrib.auth import get_user_model, logout ,authenticate, login
from django.db import transaction
from django.urls import reverse
from .forms import PassengerSignUpForm
from .models import Passenger



def home(request):
    return render(request, 'welcome.html')


User = get_user_model()




def sign_up(request):
    passenger_signup_form = PassengerSignUpForm()

    if request.method == 'POST':
        form = PassengerSignUpForm(request.POST)

        if form.is_valid():
            user = User.objects.create_user(
                email=form.cleaned_data['email'],
                username=form.cleaned_data['email'],  # Use the email as the username
                password=form.cleaned_data['password'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                role=User.Role.TAXIPASSENGER
            )

            passenger = Passenger(user=user)
            # Update passenger fields here
            passenger.save()

            # Authenticate and log in the user
            user = authenticate(request, username=user.email, password=form.cleaned_data['password'])
            login(request, user)

            messages.success(request, "You have successfully signed up as a passenger.")
            return redirect('passenger:book-a-taxi')  # Replace 'home' with the desired URL after login

    return render(request, 'sign-up.html', {
        'passenger_signup_form': passenger_signup_form,
    })








# class CustomLogoutView(TemplateView):
#     template_name = 'welcome.html'

#     def dispatch(self, request, *args, **kwargs):
#         logout(request)
#         return render(request, 'welcome.html')


# class PassengerLoginView(LoginView):
#     template_name = 'registration/passenger-login.html'
#     success_url = ('passenger:profile')

# class DriverLoginView(LoginView):
#     template_name = 'registration/driver-login.html'
#     success_url = reverse_lazy('driver:trip-view')



# def sign_up(request):
#     passenger_signup_form = forms.PassengerSignUpForm()
#     driver_signup_form = forms.DriverSignUpForm()

#     if request.method == 'POST':
#         form_type = request.POST.get('form_type')

#         if form_type == 'passenger_signup':
#             form = forms.PassengerSignUpForm(request.POST)
#             role = get_user_model().Role.TAXIPASSENGER
#         elif form_type == 'driver_signup':
#             form = forms.DriverSignUpForm(request.POST)
#             role = get_user_model().Role.TAXIDRIVER
#         else:
#             form = None
#             role = None

#         if form and form.is_valid():
#             with transaction.atomic():
#                 user = get_user_model().objects.create_user(
#                     email=form.cleaned_data['email'],
#                     username=form.cleaned_data['email'],  # Use the email as the username
#                     password=form.cleaned_data['password'],
#                     first_name=form.cleaned_data['first_name'],
#                     last_name=form.cleaned_data['last_name'],
#                     role=role
#                 )

#                 if role == get_user_model().Role.TAXIPASSENGER:
#                     passenger = Passenger(user=user)
#                     # Update passenger fields here
#                     passenger.save()

#                     messages.success(request, "You have successfully signed up as a passenger.")
#                     return redirect('passenger-login')
#                 elif role == get_user_model().Role.TAXIDRIVER:
#                     driver = Driver(user=user)
#                     # Update driver fields here
#                     driver.save()

#                     messages.success(request, "You are already registered as a driver. Please log in.")
#                     return redirect('driver-login')
#                 else:
#                     form = None
#                     role = None
#                     messages.error(request, "Unfortunately, an error occurred. Please try again.")
#                     return redirect('sign-up')

#     return render(request, 'sign-up.html', {
#         'passenger_signup_form': passenger_signup_form,
#         'driver_signup_form': driver_signup_form,
#     })

core/templates/passenger/base.html
{% extends 'base.html' %}
{% include 'messages.html' %}
{% load static %}

{% block head %}

{% endblock %}

{% block content %}
{% url 'passenger:book-a-taxi' as book_taxi_url %}
{% url 'passenger:my-trips' as my_trips_url %}
{% url 'passenger:profile' as profile_url %}
{% url 'passenger:payment-method' as payment_method_url %}

<div class="container shadow-lg bg-body-tertiary rounded bg-light mb-4 mt-4 pt-3 pb-3">
    <div class="row">
        <div class="col-lg-4">
            <div class="text-center">
                <img src="{% if request.user.passenger.profile_photo %}{{ request.user.passenger.profile_photo.url }}{% else %}{% static 'images/avatar.png'%}{% endif %}" class="rounded-circle mb-2" alt="avatar-image" width="100" height="100">
                <h4>{{ request.user.get_full_name }}</h4>
                <p>{{ request.user.email }}</p>
            </div>

            <div class="list-group mt-5">
                <a href="{% url 'passenger:book-a-taxi' %}" class="list-group-item list-group-item-action{% if request.path == book_taxi_url %} active {% endif %}">Book a Taxi</a>
                <a href="{% url 'passenger:my-trips' %}" class="list-group-item list-group-item-action {% if request.path == my_trips_url %} active {% endif %}">My Trips</a>
                <a href="{% url 'passenger:profile' %}" class="list-group-item list-group-item-action {% if request.path == profile_url %} active {% endif %}">Profile Information</a>
                <a href="{% url 'passenger:payment-method' %}" class="list-group-item list-group-item-action {% if request.path == payment_method_url %} active {% endif %}">Payments Details</a>
            </div>
        </div>
        <div class="col-lg-8 mt-3">
            {% block main %}
            {% endblock %}
        </div>
    </div>
</div>

<!-- Success Modal -->
<div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content bg-success">
            <div class="modal-body">
                <div class="alert" role="alert">
                    <strong style="color: white; font-weight:bold;">Successful</strong> <span style="color: white;">{{ message }}  &#x1F44D;</span>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Error Modal -->
<div class="modal fade" id="errorModal" tabindex="-1" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content bg-danger">
            <div class="modal-body">
                <div class="alert" role="alert">
                    <strong style="color: white; font-weight:bold;">Error</strong> <span style="color: white;">{{ message }}  &#x1F614;</span>
                </div>
            </div>
        </div>
    </div>
</div>

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <script>
                $(document).ready(function() {
                    // Show the success modal
                    $('#successModal').modal('show');
                });
            </script>
        {% elif message.tags == 'error' %}
            <script>
                $(document).ready(function() {
                    // Show the error modal
                    $('#errorModal').modal('show');
                });
            </script>
        {% endif %}
    {% endfor %}
{% endif %}
{% endblock content %}

core/templates/passenger/book-taxi.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <div class="row">
        <!--LEFT SIDE-->
        <div class="col-lg-4">
            <div class="card">
                <div class="card-header">
                    TRIP SUMMARY
                </div>
                <div class="card-body">
                    <p> A summary of your trip will appear here.</p>
                </div>
            </div>
        </div>
        <!--RIGHT SIDE-->
        <div class="col-lg-8">
            <div class="card mb-5">
            <div class="card-body"></div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

core/templates/passenger/my-trips.html
{% extends 'passenger/base.html' %}
{% load bootstrap5 %}
{% load static %}

{% block main %}
  <h1>My Trips</h1>
  {% if no_trips %}
    <p>No trips found.</p>
  {% else %}
    {% for trip in trips %}
    {% if trip.taxi_booking_status == 'booked' %}
      <div class="card ">
        <div class="card-header">
          Details
          <!-- Showing the relevant badge if trip is booked or cancelled -->
          <span class="badge float-end bg-success text-bg-info"> {{ trip.taxi_booking_status }}</span>

        </div>
        <!--If the trip is booked it show all the details of the trip otherwise if cancelled just show minor details-->
        <div class="card-body shadow-lg p-4">
          <p class="card-text"><strong>Pickup Location: </strong>{{ trip.pickup_address }}</p>
          <p class="card-text"><strong>Destination: </strong>{{ trip.dropoff_address }}</p>
          <p class="card-text"><strong>Pickup Time: </strong>{{ trip.pickup_datetime }}</p>
          <p class="card-text"><strong>Distance: </strong>{{ trip.trip_distance }}</p>
          <p class="card-text"><strong>Description: </strong>{{ trip.description }}</p>
          <!-- shwoing relevant times according to the booking status -->
          <span class="fw-light float-end" style="font-size:12px;color:grey;"> Booked at: {{ trip.booking_time}}</span>
          <!-- If trip is cancelled the cancel button is disabled -->
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#cancelModal{{ trip.id }}">
            Cancel Trip
          </button>
        </div>
      </div>
      {% elif trip.taxi_booking_status == 'cancelled' %}
<div class="card mt-4" style="background-color:#ffebee">
  <div class="card-body">
      <div>
        <span class="badge float-end bg-danger text-bg-info"> {{ trip.taxi_booking_status }}</span>

          <p class="card-text"><strong> {{ trip.pickup_address }}</strong><p>To</p><strong> {{ trip.dropoff_address }}</strong></p>
          <!-- shwoing relevant times according to the booking status -->
          <span class="fw-light float-end" style="font-size:12px;color:grey;"> Cancelled at: {{ trip.cancellation_time}}</span>
    </div>
  </div>
</div>
      {% endif %}
      <!-- Cancel Trip Modal -->
      <div class="modal fade" id="cancelModal{{ trip.id }}" tabindex="-1" aria-labelledby="cancelModalLabel{{ trip.id }}" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="cancelModalLabel{{ trip.id }}">Confirm Cancellation</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to cancel the trip?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" id="closeModal{{ trip.id }}" data-bs-dismiss="modal">Close</button>
              <form action="{% url 'passenger:cancel-trip' trip.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Cancel Trip</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  {% endif %}
{% endblock %}

core/templates/passenger/payment-method.html
{% extends 'passenger/base.html' %}
{% load bootstrap5 %}

{% block head %}
<script src="https://js.stripe.com/v3/"></script>
<style>
    #setup-form {
        padding: 2rem;
    }

    #card-element {
        height: auto;
        padding: 10px 12px;
        width: 100%;
        background-color: white;
        border: 1px solid #ced4da;
        border-radius: 4px;
    }

    #card-element--focus {
        border-color: #80bdff;
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, .25);
    }

    #card-element--invalid {
        border-color: #fa755a;
    }

    #card-element--webkit-autofil {
        background-color: #fefde5 !important;
    }
</style>
{% endblock %}

{% block main %}
{% if not request.user.passenger.stripe_payment_method_id %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    Let's add your Card first, to <strong>Book a Taxi</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

<b class="text-secondary">Your Credit/Debit Card</b>
<div class="card bg-white mt-3">
    <div class="card-body">

        {% if request.user.passenger.stripe_payment_method_id %}
        <div id="change-card" class="input-group">
            <input type="text" class="form-control" disabled
                value=" **** **** **** {{ request.user.passenger.stripe_card_last4 }}">
            <div class="input-group-append">
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Remove</button>
                </form>
            </div>
        </div>

        {% else %}
        <form id="setup-form" data-secret="{{ client_secret }}">
            <div id="card-element">
                <!-- Elements will create form elements here -->
            </div>
            <button id="card-button" type="button" class="btn btn-warning mt-3">Save Card</button>
        </form>
        {% endif %}
    </div>
</div>

{% if not request.user.passenger.stripe_payment_method_id %}
<script>
    var stripe = Stripe("{{STRIPE_API_PUBLIC_KEY}}");

    var elements = stripe.elements();
    var cardElement = elements.create('card');
    cardElement.mount('#card-element');

    var cardButton = document.getElementById('card-button');
    var clientSecret = "{{ client_secret }}";

    cardButton.addEventListener('click', function (ev) {
        stripe.confirmCardSetup(
            clientSecret,
            {
                payment_method: {
                    card: cardElement,
                },
            }
        ).then(function (result) {
            if (result.error) {
                toast(result.error.message, 'error');
            } else {
                toast(result.message, 'success');
                location.reload(); // Reload the page after saving the card
            }
        });
    });
</script>
{% endif %}
{% endblock %}

core/templates/passenger/profile.html
{% extends 'passenger/base.html' %}
{% load bootstrap5 %}

{% block head %}

{% endblock %}

{% block main %}
<b class="text-secondary">Basic Information</b>
<div class="card bg-white mt-3 mb-3">
    <div class="card-body">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form user_form %}
            {% bootstrap_form passenger_form %}
            <input type="hidden" name="action" value="update_profile">
            <button type="submit" id="liveAlertBtn" class="btn btn-warning">Save</button>
        </form>
    </div>
</div>


{% comment %} Change Password {% endcomment %}
<b class="text-secondary">Change Password</b>
<div class="card bg-white mt-2 mb-5">
    <div class="card-body">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form password_form %}
            <input type="hidden" name="action" value="update_password">
            <button type="submit" class="btn btn-warning">Save</button>
        </form>
    </div>
</div>

{% endblock %}