core/urls.py
from django.urls import path
from core import views
from django.urls import path, include
from . import views
from core.passenger import views as passenger_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('sign-up/', views.sign_up, name='sign-up'),
    # Add other URL patterns for core app

    # Add the passenger app patterns
    path('passenger/', include((
        [
            path('', passenger_views.home, name="passenger-home"),
            path('profile/', passenger_views.profile_page, name="profile"),
            path('payment-method/', passenger_views.payment_method_page, name="payment-method"),
            path('book-a-taxi/', passenger_views.book_taxi_page, name="book-a-taxi"),
            path('my-trips/', passenger_views.my_trips_page, name="my-trips"),
            path('cancel-trip/<uuid:trip_id>/', passenger_views.cancel_trip, name='cancel-trip'),
        ],
        'passenger'
    ), namespace='passenger')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taximate/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from core import views as core_views
from core.passenger import views as passenger_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_views.home, name='home'),
    path('sign-up/', core_views.sign_up, name="sign-up"),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    
    # Passenger views
    path('passenger/', include(([
        path('', passenger_views.home, name="passenger-home"),
        path('profile/', passenger_views.profile_page, name="profile"),
        path('payment-method/', passenger_views.payment_method_page, name="payment-method"),
        path('book-a-taxi/', passenger_views.book_taxi_page, name="book-a-taxi"),
        path('my-trips/', passenger_views.my_trips_page, name="my-trips"),
        path('cancel-trip/<uuid:trip_id>/', passenger_views.cancel_trip, name='cancel-trip'),
    ], 'passenger'), namespace='passenger')),
    
    # Other URL patterns
    
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import User

class PassengerSignUpForm(forms.ModelForm):
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password', 'required': True}),
    )
    email = forms.EmailField(
        max_length=250,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email Address', 'required': True}),
    )
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username', 'required': True}),
    )
    first_name = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name', 'required': True}),
    )
    last_name = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name', 'required': True}),
    )

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email address is already registered.")
        return email

core/passenger/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from core.passenger import forms
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.conf import settings
import stripe
from core.models import Taxi, Passenger, MyTrips
from django.utils import timezone
import googlemaps
from googlemaps import convert
from googlemaps import distance_matrix
from django.utils.text import slugify
from .forms import TaxiBookingForm
from datetime import datetime
from django.utils.timezone import now
from .forms import BasicUserForm, BasicCustomerForm
from django.http import HttpResponseRedirect,HttpRequest
from core.models import TaxiPassenger,TaxiDriver,User
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from core.models import Passenger
from django.core.exceptions import ObjectDoesNotExist



User = get_user_model()

def home(request):
    return render(request, "welcome.html")



@login_required(login_url="/login/?next=/passenger/")
def profile_page(request):
    user_form = BasicUserForm(instance=request.user)
    passenger_form = BasicCustomerForm(instance=request.user.passenger)
    password_form = PasswordChangeForm(request.user)

    if request.method == "POST":
        if request.POST.get('action') == 'update_profile':
            user_form = BasicUserForm(request.POST, instance=request.user)
            passenger_form = BasicCustomerForm(request.POST, request.FILES, instance=request.user.passenger)
            if user_form.is_valid() and passenger_form.is_valid():
                user_form.save()
                passenger_form.save()

                messages.success(request, 'Profile updated successfully.')
                return redirect(reverse('passenger:profile'))

        elif request.POST.get('action') == 'update_password':
            password_form = PasswordChangeForm(request.user, request.POST)
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)

                messages.success(request, 'Password updated successfully.')
                return redirect(reverse('passenger:profile'))

    return render(request, 'passenger/profile.html', {
        "user_form": user_form,
        "passenger_form": passenger_form,
        "password_form": password_form,
    })



# BOOKING TAXI

@login_required(login_url="/login/?next=/passenger/")

def book_taxi_page(request):
    if not request.user.is_authenticated or not hasattr(request.user, 'passenger'):
        return redirect('login')

    if request.method == "POST":
        pickup_form = TaxiBookingForm(request.POST)
        if pickup_form.is_valid():
            passenger = request.user.passenger

            # Validate pickup address
            gmaps = googlemaps.Client(key=settings.GOOGLE_MAPS_API_KEY)
            pickup_address = pickup_form.cleaned_data['pickup_address']
            pickup_geocode_result = gmaps.geocode(pickup_address)
            if not pickup_geocode_result:
                messages.error(request, "Invalid pickup address. Please enter a valid address.")
                return redirect(reverse('passenger:book-a-taxi'))
            pickup_location = pickup_geocode_result[0]['geometry']['location']
            pickup_lat = pickup_location['lat']
            pickup_lng = pickup_location['lng']

            # Validate dropoff address
            dropoff_address = pickup_form.cleaned_data['dropoff_address']
            dropoff_geocode_result = gmaps.geocode(dropoff_address)
            if not dropoff_geocode_result:
                messages.error(request, "Invalid dropoff address. Please enter a valid address.")
                return redirect(reverse('passenger:book-a-taxi'))
            dropoff_location = dropoff_geocode_result[0]['geometry']['location']
            dropoff_lat = dropoff_location['lat']
            dropoff_lng = dropoff_location['lng']

            # Calculate the distance using Google Maps Distance Matrix API
            origins = f"{pickup_lat},{pickup_lng}"
            destinations = f"{dropoff_lat},{dropoff_lng}"
            result = gmaps.distance_matrix(origins, destinations, mode='driving')

            # Extract the distance value from the API response
            distance = result['rows'][0]['elements'][0]['distance']['value']
            # Convert distance to kilometers (optional)
            distance_km = distance / 1000

            # Create a new booking instance
            taxi_booking = Taxi(
                taxi_passenger=passenger,
                pickup_address=pickup_address,
                pickup_lat=pickup_lat,
                pickup_lng=pickup_lng,
                dropoff_address=dropoff_address,
                dropoff_lat=dropoff_lat,
                dropoff_lng=dropoff_lng,
                trip_distance=distance_km,
                pickup_datetime=datetime.now(),
                taxi_booking_status=Taxi.TRIP_BOOKED
            )
            taxi_booking.save()

            # Create MyTrips instance
            my_trip = MyTrips(
                booked_passenger=passenger,
                booked_taxi=taxi_booking,
            )
            my_trip.save()

            # Add success message
            messages.success(request, "Booking created successfully!")

            return redirect(reverse('passenger:my-trips'))
        else:
            # Add error messages for form fields with invalid data
            for field, errors in pickup_form.errors.items():
                for error in errors:
                    messages.error(request, f"Invalid {field}: {error}")
    else:
        pickup_form = TaxiBookingForm()

    return render(request, 'passenger/book-a-taxi.html', {
        "pickup_form": pickup_form,
    })
# CANCEL THE TRIP LOGIC

def cancel_trip(request, trip_id):
    try:
        trip = Taxi.objects.get(id=trip_id)
        trip.taxi_booking_status = Taxi.TRIP_CANCELLED  # Update the booking status to 'Trip Cancelled'
        trip.save()

        my_trip = MyTrips.objects.get(booked_taxi=trip)
        my_trip.save()

        messages.success(request, "Trip cancelled successfully!")
    except Taxi.DoesNotExist:
        messages.error(request, "Trip not found.")

    return redirect('passenger:my-trips')

#  PASSENGER TRIPS
@login_required(login_url="/login/?next=/passenger/")

def my_trips_page(request):
    try:
        passenger = request.user.passenger
        booked_trips = Taxi.objects.filter(taxi_passenger=passenger, taxi_booking_status=Taxi.TRIP_BOOKED).order_by('pickup_datetime')
        canceled_trips = Taxi.objects.filter(taxi_passenger=passenger, taxi_booking_status=Taxi.TRIP_CANCELLED).order_by('cancellation_time')

        trips = list(booked_trips) + list(canceled_trips)

        context = {
            'trips': trips,
        }

        return render(request, 'passenger/my-trips.html', context)

    except ObjectDoesNotExist:
        # Handle the case when the user does not have a related passenger object
        # You can adjust this part to fit your desired behavior or redirect the user to an appropriate page
        return render(request, 'passenger/my-trips.html', {'no_passenger': True})



#Payment Method

stripe.api_key = settings.STRIPE_SECRET_KEY

@login_required(login_url="/login/?next=/passenger/")

def payment_method_page(request):
    try:
        passenger = request.user.passenger
    except AttributeError:
        return redirect('login')

    if request.method == 'POST':
        stripe.PaymentMethod.detach(passenger.stripe_payment_method_id)
        passenger.stripe_payment_method_id = ''
        passenger.stripe_card_last4 = ''
        passenger.save()
        return redirect('passenger:payment-method')

    if not passenger.stripe_customer_id:
        customer = stripe.Customer.create()
        passenger.stripe_customer_id = customer['id']
        passenger.save()

    stripe_payment_methods = stripe.PaymentMethod.list(
        customer=passenger.stripe_customer_id,
        type='card',
    )

    if stripe_payment_methods and len(stripe_payment_methods.data) > 0:
        payment_method = stripe_payment_methods.data[0]
        passenger.stripe_payment_method_id = payment_method.id
        passenger.stripe_card_last4 = payment_method.card.last4
        passenger.save()
    else:
        passenger.stripe_payment_method_id = ''
        passenger.stripe_card_last4 = ''
        passenger.save()

    client_secret = stripe.SetupIntent.create(
        customer=passenger.stripe_customer_id,
        payment_method_types=['card'],
    ).client_secret

    return render(request, 'passenger/payment-method.html', {
        'passenger': passenger,
        'client_secret': client_secret,
        'STRIPE_API_PUBLIC_KEY': settings.STRIPE_API_PUBLIC_KEY,
    })

core/views.py
from django.urls import reverse_lazy
from .models import User,TaxiPassenger,TaxiDriver,Driver,Passenger
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from . import forms
from django.contrib.auth import get_user_model, logout ,authenticate, login
from django.db import transaction
from django.urls import reverse
from .forms import PassengerSignUpForm
from .models import Passenger



def home(request):
    return render(request, 'welcome.html')


User = get_user_model()




def sign_up(request):
    passenger_signup_form = PassengerSignUpForm()

    if request.method == 'POST':
        form = PassengerSignUpForm(request.POST)

        if form.is_valid():
            user = User.objects.create_user(
                email=form.cleaned_data['email'],
                username=form.cleaned_data['email'],  # Use the email as the username
                password=form.cleaned_data['password'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                role=User.Role.TAXIPASSENGER
            )

            passenger = Passenger(user=user)
            # Update passenger fields here
            passenger.save()

            # Authenticate and log in the user
            user = authenticate(request, username=user.email, password=form.cleaned_data['password'])
            login(request, user)

            messages.success(request, "You have successfully signed up as a passenger.")
            return redirect('passenger:book-a-taxi')  # Replace 'home' with the desired URL after login

    return render(request, 'sign-up.html', {
        'passenger_signup_form': passenger_signup_form,
    })








# class CustomLogoutView(TemplateView):
#     template_name = 'welcome.html'

#     def dispatch(self, request, *args, **kwargs):
#         logout(request)
#         return render(request, 'welcome.html')


# class PassengerLoginView(LoginView):
#     template_name = 'registration/passenger-login.html'
#     success_url = ('passenger:profile')

# class DriverLoginView(LoginView):
#     template_name = 'registration/driver-login.html'
#     success_url = reverse_lazy('driver:trip-view')



# def sign_up(request):
#     passenger_signup_form = forms.PassengerSignUpForm()
#     driver_signup_form = forms.DriverSignUpForm()

#     if request.method == 'POST':
#         form_type = request.POST.get('form_type')

#         if form_type == 'passenger_signup':
#             form = forms.PassengerSignUpForm(request.POST)
#             role = get_user_model().Role.TAXIPASSENGER
#         elif form_type == 'driver_signup':
#             form = forms.DriverSignUpForm(request.POST)
#             role = get_user_model().Role.TAXIDRIVER
#         else:
#             form = None
#             role = None

#         if form and form.is_valid():
#             with transaction.atomic():
#                 user = get_user_model().objects.create_user(
#                     email=form.cleaned_data['email'],
#                     username=form.cleaned_data['email'],  # Use the email as the username
#                     password=form.cleaned_data['password'],
#                     first_name=form.cleaned_data['first_name'],
#                     last_name=form.cleaned_data['last_name'],
#                     role=role
#                 )

#                 if role == get_user_model().Role.TAXIPASSENGER:
#                     passenger = Passenger(user=user)
#                     # Update passenger fields here
#                     passenger.save()

#                     messages.success(request, "You have successfully signed up as a passenger.")
#                     return redirect('passenger-login')
#                 elif role == get_user_model().Role.TAXIDRIVER:
#                     driver = Driver(user=user)
#                     # Update driver fields here
#                     driver.save()

#                     messages.success(request, "You are already registered as a driver. Please log in.")
#                     return redirect('driver-login')
#                 else:
#                     form = None
#                     role = None
#                     messages.error(request, "Unfortunately, an error occurred. Please try again.")
#                     return redirect('sign-up')

#     return render(request, 'sign-up.html', {
#         'passenger_signup_form': passenger_signup_form,
#         'driver_signup_form': driver_signup_form,
#     })

core/templates/base.html
<!doctype html>
<html lang="en">



<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>

    {% load bootstrap5  %} {% bootstrap_css %} {% bootstrap_javascript %}
    {% load static %}
         <!-- Include Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

      <!-- Include jQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

      <!-- Include Bootstrap JS -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


     <!-- Include Bootstrap JavaScript -->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"></script>

     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.4.0/css/all.css">

    {% block head %}{% endblock %}
</head>

<body>
      <nav id="navbar-container"  class="navbar  navbar-light{% if not request.user.is_authenticated %} navbar-expand-xl {% endif %}{% if not request.user.is_authenticated %} navbar-expand-xl {% endif %} bg-warning">
         <a class="navbar-brand fs-4 fw-bolder ms-5" id="nav-logo" {% if request.user.is_authenticated and request.user.passenger %}href="{% url 'passenger:profile' %}"{% else %}href="{% url 'home' %}"{% endif %}>Taksy</a>
        {% if not request.user.is_authenticated %}
        {% else %}
         <form action="form-inline">
            <img src="{% if request.user.passenger.profile_photo %}{{ request.user.passenger.profile_photo.url }}{% else %}{% static 'images/avatar.png'%}{% endif %}" class="rounded-circle me-2" alt="avatar-image" width="50" height="50">
            <a class="me-4 fw-bold " style="text-decoration:none; color:black;" href="{% url 'passenger:profile'%}">{{ request.user.get_full_name|title }}</a>
            <a href="/logout/" class=" btn me-4 btn-dark">Logout</a>
         </form>
   {% endif %}
      </nav>

   {% block content %}{% endblock %}
    <footer class="mt-5 mb-5 text-center "> &copy;Taksy</footer>

</body>

</html>

core/templates/home.html
{% extends 'base.html' %}

{% block head %}
<style>
    body {
        background-color: #ffc107;
    }

    .section-welcome {
        text-align: center;
        padding: 50px 0;
    }

    .fade-in {
        animation: fade-in 1s ease-in-out;
    }

    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }

    .card {
        width: 300px;
        border: none;
        background-color: white;
        transition: transform 0.3s ease-in-out;
        margin-bottom: 20px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        background-color: #ffc107;
    }

    .btn {
        background-color: black;
        color: white;
        width: 100%;
        padding: 12px 20px;
        font-size: 16px;
        font-weight: bold;
        border-radius: 4px;
        margin-bottom: 10px;
        box-shadow: 0px 2px 6px rgba(0, 0, 0, 0.1);
    }

    .btn:hover {
        transform: scale(1.02);
    }

    .fade-in-left {
        animation: slide-in-left 1s ease-in-out;
    }

    @keyframes slide-in-left {
        0% {
            transform: translateX(-100%);
            opacity: 0;
        }
        80% {
            transform: translateX(10%);
            opacity: 1;
        }
        100% {
            transform: translateX(0);
            opacity: 1;
        }
    }





</style>
{% endblock %}

{% block content %}

<section class="section-welcome">
    <div class="clo-lg-12 text-center mt-5">
        <h1 id="welcome-text" class="text-uppercase smoke fade-in-left" style="color: black;">Welcome to Taksi</h1>
    </div>
</section>

<div class="container">
    <div class="card fade-in">
        <a href="{% url 'passenger:passenger-home' %}" class="btn btn-warning">Passenger login</a>
        <a href="{% url 'driver:driver-home' %}" class="btn btn-warning">Driver login</a>
    </div>
</div>
{% endblock %}

core/templates/sign-up.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block head %}
<title>Taksy | Passenger</title>
{% endblock  %}
{% block content %}
<div class="container-fluid mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="toast align-items-center text-white {% if message.tags %} bg-{{ message.tags }} {% endif %}" role="alert" aria-live="assertive" aria-atomic="true">
                                <div class="d-flex">
                                    <div class="toast-body">
                                        {{ message }}
                                    </div>
                                    <button type="button" class="btn-close ms-auto me-2" data-bs-dismiss="toast" aria-label="Close"></button>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <h4 class="text-center text-uppercase mb-3">
                        <b>Passenger</b>
                    </h4>
                    <form method="POST" action="{% url 'sign-up' %}">
                        {% csrf_token %}
                        {% bootstrap_form passenger_signup_form %}
                        <div class="d-grid gap-2">
                            <button class="btn btn-success btn-block {% if passenger_signup_form.is_valid %} is_valid {% endif %}" type="submit">
                                {% if passenger_signup_form.is_bound and passenger_signup_form.is_valid %}
                                    <i class="bi bi-check-circle-fill"></i> Sign Up
                                {% else %}
                                    <i class="bi bi-emoji-frown-fill"></i> Sign Up
                                {% endif %}
                            </button>
                        </div>
                        <p class="text-center mt-3">Already have an account?
                            <a href="{% url 'passenger:profile' %}?next={{ request.GET.next }}">Log In</a>
                        </p>
                        <input type="hidden" name="form_type" value="passenger_signup">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/welcom_email_template.html
Hi {{ name }}

We are Delighted to have you join us!

Founder if Taxi Pal
Shah Bakhat

core/templates/welcome-email.html
Hi {{ name }}

We are Delighted to have you join us!



Founder of Taksi
Shah Bakhat

core/templates/welcome.html
{% extends 'base.html' %}

{% block head %}
<style>
    body {
        background-color: #ffc107;
    }

    .section-welcome {
        text-align: center;
        padding: 50px 0;
    }

    .fade-in {
        animation: fade-in 1s ease-in-out;
    }

    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }

    .card {
        width: 300px;
        border: none;
        background-color: white;
        transition: transform 0.3s ease-in-out;
        margin-bottom: 20px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        background-color: #ffc107;
    }

    .btn {
        background-color: black;
        color: white;
        width: 100%;
        padding: 12px 20px;
        font-size: 16px;
        font-weight: bold;
        border-radius: 4px;
        margin-bottom: 10px;
        box-shadow: 0px 2px 6px rgba(0, 0, 0, 0.1);
    }

    .btn:hover {
        transform: scale(1.02);
    }

    .fade-in-left {
        animation: slide-in-left 1s ease-in-out;
    }

    @keyframes slide-in-left {
        0% {
            transform: translateX(-100%);
            opacity: 0;
        }
        80% {
            transform: translateX(10%);
            opacity: 1;
        }
        100% {
            transform: translateX(0);
            opacity: 1;
        }
    }





</style>
{% endblock %}

{% block content %}

<section class="section-welcome">
    <div class="clo-lg-12 text-center mt-5">
        <h1 id="welcome-text" class="text-uppercase smoke fade-in-left" style="color: black;">Welcome to Taksy</h1>
    </div>
</section>

<div class="container">
    <div class="card fade-in">
        <a href="{% url 'passenger:profile' %}" class="btn btn-warning">Passenger login</a>
        <a class="btn btn-warning" href="{% url 'sign-up' %}">Create an account</a>
    </div>
</div>
{% endblock %}

core/templates/welcome_email_template.html
Hi {{ name }}

We are Delighted to have you join us!



Founder of Taksi
Shah Bakhat